# Generated by Django 6.0.6 on 2026-06-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'nivel académico',
                'db_table': 'nivel_academico',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de autorización',
                'db_table': 'tipo_autorizacion',
            },
        ),
        migrations.CreateModel(
            name='ClosureReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'motivo de cierre',
                'db_table': 'motivo_cierre',
            },
        ),
        migrations.CreateModel(
            name='Conapres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Denominación', max_length=255, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'CONAPRES',
                'db_table': 'conapres',
            },
        ),
        migrations.CreateModel(
            name='ConventionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
                ('aplica_a', models.CharField(choices=[('TODOS', 'Todos'), ('ESPECIFICO', 'Específico')], default='TODOS', help_text='Tipo de convenio al que aplica el estado', max_length=20, verbose_name='aplica a')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden en el flujo', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'estado de convenio',
                'db_table': 'estado_convenio',
            },
        ),
        migrations.CreateModel(
            name='ConventionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la plantilla', max_length=255, verbose_name='nombre')),
                ('referencia_externa', models.CharField(help_text='Referencia externa del archivo de plantilla', max_length=500, verbose_name='referencia externa')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión', verbose_name='versión')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
            ],
            options={
                'verbose_name': 'plantilla de convenio',
                'db_table': 'plantilla_convenio',
            },
        ),
        migrations.CreateModel(
            name='ConventionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
                ('anios_vigencia', models.PositiveSmallIntegerField(help_text='Vigencia en años (Marco=4, Específico=3)', verbose_name='años de vigencia')),
            ],
            options={
                'verbose_name': 'tipo de convenio',
                'db_table': 'tipo_convenio',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='ExecutingUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de unidad ejecutora',
                'db_table': 'tipo_unidad_ejecutora',
            },
        ),
        migrations.CreateModel(
            name='ExecutivePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'cargo ejecutivo',
                'db_table': 'cargo_ejecutivo',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la facultad', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'facultad',
                'db_table': 'facultad',
            },
        ),
        migrations.CreateModel(
            name='HealthGeographicScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'ámbito geográfico sanitario',
                'db_table': 'ambito_geografico_sanitario',
            },
        ),
        migrations.CreateModel(
            name='MinsaOrganType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de órgano del MINSA',
                'db_table': 'tipo_organo_minsa',
            },
        ),
        migrations.CreateModel(
            name='ObservationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'motivo de observación',
                'db_table': 'motivo_observacion',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'región',
                'verbose_name_plural': 'regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='RegionalOrganType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de órgano regional',
                'db_table': 'tipo_organo_regional',
            },
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'motivo de rechazo',
                'db_table': 'motivo_rechazo',
            },
        ),
        migrations.CreateModel(
            name='SigningAuthorityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de autoridad firmante',
                'db_table': 'tipo_autoridad_firmante',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'especialidad',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='UniversityEntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de entidad de universidad',
                'db_table': 'tipo_entidad_universidad',
            },
        ),
        migrations.CreateModel(
            name='UniversityManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de gestión de universidad',
                'db_table': 'tipo_gestion_universidad',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='CREAR / ACTUALIZAR / ELIMINAR / CAMBIO_ESTADO / …', max_length=30, verbose_name='acción')),
                ('id_objeto', models.PositiveBigIntegerField(help_text='Registro afectado', verbose_name='id objeto')),
                ('nombre_campo', models.CharField(blank=True, help_text='Campo modificado', max_length=100, verbose_name='nombre del campo')),
                ('valor_anterior', models.TextField(blank=True, help_text='Valor anterior', verbose_name='valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, help_text='Valor nuevo', verbose_name='valor nuevo')),
                ('direccion_ip', models.CharField(blank=True, help_text='IP de origen', max_length=45, verbose_name='dirección IP')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora', verbose_name='creado en')),
                ('tipo_contenido', models.ForeignKey(db_column='tipo_contenido_id', help_text='Entidad afectada', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', help_text='Usuario que ejecutó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bitácora de auditoría',
                'db_table': 'bitacora_auditoria',
            },
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código oficial', max_length=50, verbose_name='código')),
                ('titulo', models.CharField(help_text='Título / denominación', max_length=255, verbose_name='título')),
                ('solicitante_id_objeto', models.PositiveBigIntegerField(help_text='Identificador de la entidad solicitante', verbose_name='id objeto solicitante')),
                ('fecha_solicitud', models.DateField(help_text='Fecha de solicitud', verbose_name='fecha de solicitud')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Inicio de vigencia', null=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fin de vigencia', null=True, verbose_name='fecha de fin')),
                ('max_campos_clinicos', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de campos clínicos (solo Específico)', null=True, verbose_name='máximo de campos clínicos')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('convenio_marco', models.ForeignKey(blank=True, db_column='convenio_marco_id', help_text='Convenio Marco vigente del que depende el Específico (RN-3)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios_especificos', to='convenios.convention')),
                ('creado_por', models.ForeignKey(db_column='creado_por', help_text='Usuario que registró', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante_tipo_contenido', models.ForeignKey(db_column='solicitante_tipo_contenido_id', help_text='Tipo de entidad solicitante', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('estado_actual', models.ForeignKey(db_column='estado_actual_id', help_text='Estado actual', on_delete=django.db.models.deletion.PROTECT, to='convenios.conventionstatus')),
                ('plantilla', models.ForeignKey(blank=True, db_column='plantilla_id', help_text='Plantilla utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='convenios.conventiontemplate')),
                ('tipo_convenio', models.ForeignKey(db_column='tipo_convenio_id', help_text='Marco / Específico', on_delete=django.db.models.deletion.PROTECT, to='convenios.conventiontype')),
            ],
            options={
                'verbose_name': 'convenio',
                'db_table': 'convenio',
            },
        ),
        migrations.CreateModel(
            name='ConapresOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(help_text='Fecha de solicitud de opinión', verbose_name='fecha de solicitud')),
                ('estado_atencion', models.CharField(help_text='Estado de atención', max_length=20, verbose_name='estado de atención')),
                ('resultado_opinion', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('OBSERVADO', 'Observado')], help_text='Resultado', max_length=20, verbose_name='resultado de la opinión')),
                ('fecha_respuesta', models.DateField(blank=True, help_text='Fecha de respuesta', null=True, verbose_name='fecha de respuesta')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio (solo Específico)', on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_conapres', to='convenios.convention')),
            ],
            options={
                'verbose_name': 'opinión CONAPRES',
                'db_table': 'opinion_conapres',
            },
        ),
        migrations.CreateModel(
            name='ConventionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambiado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora', verbose_name='cambiado en')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones', verbose_name='observación')),
                ('cambiado_por', models.ForeignKey(db_column='cambiado_por', help_text='Responsable del cambio', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='convenios.convention')),
                ('estado', models.ForeignKey(db_column='estado_id', help_text='Estado registrado', on_delete=django.db.models.deletion.PROTECT, to='convenios.conventionstatus')),
            ],
            options={
                'verbose_name': 'historial de estado de convenio',
                'db_table': 'historial_estado_convenio',
            },
        ),
        migrations.AddField(
            model_name='conventiontemplate',
            name='tipo_convenio',
            field=models.ForeignKey(db_column='tipo_convenio_id', help_text='Tipo al que aplica', on_delete=django.db.models.deletion.PROTECT, to='convenios.conventiontype'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.PositiveBigIntegerField(help_text='Registro destino', verbose_name='id objeto')),
                ('referencia_externa', models.CharField(help_text='Clave/URL del archivo en el repositorio externo', max_length=500, verbose_name='referencia externa')),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo', max_length=255, verbose_name='nombre del archivo')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión', verbose_name='versión')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('REEMPLAZADO', 'Reemplazado'), ('ANULADO', 'Anulado'), ('OBSERVADO', 'Observado'), ('VALIDADO', 'Validado')], default='ACTIVO', help_text='Estado', max_length=20, verbose_name='estado')),
                ('cargado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de carga', verbose_name='cargado en')),
                ('cargado_por', models.ForeignKey(db_column='cargado_por', help_text='Usuario que cargó', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_contenido', models.ForeignKey(db_column='tipo_contenido_id', help_text='Tabla destino', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('version_anterior', models.ForeignKey(blank=True, db_column='version_anterior_id', help_text='Versión previa reemplazada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_siguientes', to='convenios.document')),
                ('tipo_documento', models.ForeignKey(db_column='tipo_documento_id', help_text='Tipo de documento', on_delete=django.db.models.deletion.PROTECT, to='convenios.documenttype')),
            ],
            options={
                'verbose_name': 'documento',
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='ExecutingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('codigo', models.CharField(blank=True, help_text='Código presupuestal', max_length=50, verbose_name='código')),
                ('referencia_logo', models.CharField(blank=True, help_text='Referencia externa del logo (repositorio externo)', max_length=500, verbose_name='referencia del logo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo_unidad_ejecutora', models.ForeignKey(db_column='tipo_unidad_ejecutora_id', help_text='Hospital / Instituto / Red', on_delete=django.db.models.deletion.PROTECT, to='convenios.executingunittype')),
            ],
            options={
                'verbose_name': 'unidad ejecutora',
                'db_table': 'unidad_ejecutora',
            },
        ),
        migrations.CreateModel(
            name='Ipress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del establecimiento', max_length=255, verbose_name='nombre')),
                ('codigo_renipress', models.CharField(blank=True, help_text='Código RENIPRESS', max_length=20, verbose_name='código RENIPRESS')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('ambito_geografico_sanitario', models.ForeignKey(db_column='ambito_geografico_sanitario_id', help_text='Ámbito geográfico sanitario', on_delete=django.db.models.deletion.PROTECT, to='convenios.healthgeographicscope')),
                ('unidad_ejecutora', models.ForeignKey(db_column='unidad_ejecutora_id', help_text='Unidad ejecutora a la que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='ipress', to='convenios.executingunit')),
            ],
            options={
                'verbose_name': 'IPRESS',
                'verbose_name_plural': 'IPRESS',
                'db_table': 'ipress',
            },
        ),
        migrations.CreateModel(
            name='LegalOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(help_text='Fecha de envío a OGAJ', verbose_name='fecha de envío')),
                ('resultado_opinion', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('OBSERVADO', 'Observado')], help_text='Resultado', max_length=20, verbose_name='resultado de la opinión')),
                ('observaciones_legales', models.TextField(blank=True, help_text='Observaciones legales', verbose_name='observaciones legales')),
                ('subsanacion', models.TextField(blank=True, help_text='Subsanación', verbose_name='subsanación')),
                ('fecha_respuesta', models.DateField(blank=True, help_text='Fecha de respuesta', null=True, verbose_name='fecha de respuesta')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio', on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_juridicas', to='convenios.convention')),
            ],
            options={
                'verbose_name': 'opinión jurídica',
                'db_table': 'opinion_juridica',
            },
        ),
        migrations.CreateModel(
            name='MinsaOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del órgano', max_length=255, verbose_name='nombre')),
                ('siglas', models.CharField(blank=True, help_text='Siglas', max_length=50, verbose_name='siglas')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo_organo_minsa', models.ForeignKey(db_column='tipo_organo_minsa_id', help_text='DIGEP / OGAJ / SG / VICEPAS', on_delete=django.db.models.deletion.PROTECT, to='convenios.minsaorgantype')),
            ],
            options={
                'verbose_name': 'órgano del MINSA',
                'db_table': 'organo_minsa',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la carrera o programa', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('facultad', models.ForeignKey(db_column='facultad_id', help_text='Facultad', on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='convenios.faculty')),
                ('nivel_academico', models.ForeignKey(db_column='nivel_academico_id', help_text='Carrera profesional / segunda especialidad / maestría / doctorado', on_delete=django.db.models.deletion.PROTECT, to='convenios.academiclevel')),
                ('especialidad', models.ForeignKey(blank=True, db_column='especialidad_id', help_text='Especialidad asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='convenios.specialty')),
            ],
            options={
                'verbose_name': 'carrera profesional',
                'db_table': 'carrera_profesional',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(help_text='Fecha de publicación', verbose_name='fecha de publicación')),
                ('referencia_publicacion', models.CharField(blank=True, help_text='Enlace, código o constancia', max_length=255, verbose_name='referencia de publicación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio', on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='convenios.convention')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicación',
                'db_table': 'publicacion',
            },
        ),
        migrations.CreateModel(
            name='RegionalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del gobierno regional', max_length=255, verbose_name='nombre')),
                ('referencia_logo', models.CharField(blank=True, help_text='Referencia externa del logo (repositorio externo)', max_length=500, verbose_name='referencia del logo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('region', models.ForeignKey(db_column='region_id', help_text='Región', on_delete=django.db.models.deletion.PROTECT, to='convenios.region')),
            ],
            options={
                'verbose_name': 'gobierno regional',
                'db_table': 'gobierno_regional',
            },
        ),
        migrations.CreateModel(
            name='RegionalOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del órgano', max_length=255, verbose_name='nombre')),
                ('siglas', models.CharField(blank=True, help_text='Siglas', max_length=50, verbose_name='siglas')),
                ('referencia_logo', models.CharField(blank=True, help_text='Referencia externa del logo (repositorio externo)', max_length=500, verbose_name='referencia del logo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('gobierno_regional', models.ForeignKey(db_column='gobierno_regional_id', help_text='GORE al que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='organos', to='convenios.regionalgovernment')),
                ('tipo_organo_regional', models.ForeignKey(db_column='tipo_organo_regional_id', help_text='GERESA / DIRESA / DIRIS', on_delete=django.db.models.deletion.PROTECT, to='convenios.regionalorgantype')),
            ],
            options={
                'verbose_name': 'órgano regional',
                'db_table': 'organo_regional',
            },
        ),
        migrations.AddField(
            model_name='executingunit',
            name='organo_regional',
            field=models.ForeignKey(db_column='organo_regional_id', help_text='Órgano regional que la administra', on_delete=django.db.models.deletion.PROTECT, related_name='unidades_ejecutoras', to='convenios.regionalorgan'),
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.PositiveBigIntegerField(help_text='Identificador de la entidad representada', verbose_name='id objeto')),
                ('nombre', models.CharField(help_text='Nombre del representante', max_length=255, verbose_name='nombre')),
                ('origen', models.CharField(blank=True, choices=[('MINSA', 'MINSA'), ('GOBIERNO_REGIONAL', 'Gobierno Regional'), ('ASOCIACION_FACULTADES', 'Asociación de Facultades')], help_text='Solo para CONAPRES: MINSA / Gobierno Regional / Asociación de Facultades', max_length=30, verbose_name='origen')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Inicio de participación/cargo', null=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fin de participación/cargo', null=True, verbose_name='fecha de fin')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('cargo_ejecutivo', models.ForeignKey(db_column='cargo_ejecutivo_id', help_text='Cargo (catálogo)', on_delete=django.db.models.deletion.PROTECT, to='convenios.executiveposition')),
                ('tipo_contenido', models.ForeignKey(db_column='tipo_contenido_id', help_text='Tipo de entidad representada', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'representante',
                'db_table': 'representante',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmante_id_objeto', models.PositiveBigIntegerField(help_text='Identificador de la entidad firmante', verbose_name='id objeto firmante')),
                ('orden_firma', models.PositiveSmallIntegerField(blank=True, help_text='Orden en el circuito', null=True, verbose_name='orden de firma')),
                ('fecha_envio', models.DateField(blank=True, help_text='Fecha de envío', null=True, verbose_name='fecha de envío')),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha de recepción', null=True, verbose_name='fecha de recepción')),
                ('estado_firma', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FIRMADO', 'Firmado'), ('DEVUELTO', 'Devuelto')], help_text='Estado de firma', max_length=20, verbose_name='estado de firma')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o devoluciones', verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio', on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='convenios.convention')),
                ('firmante_tipo_contenido', models.ForeignKey(db_column='firmante_tipo_contenido_id', help_text='Tipo de entidad firmante', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tipo_autoridad_firmante', models.ForeignKey(blank=True, db_column='tipo_autoridad_firmante_id', help_text='Tipo de autoridad firmante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='convenios.signingauthoritytype')),
            ],
            options={
                'verbose_name': 'firma',
                'db_table': 'firma',
            },
        ),
        migrations.CreateModel(
            name='ClinicalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maxima', models.PositiveIntegerField(help_text='Cantidad máxima de campos clínicos autorizados', verbose_name='cantidad máxima')),
                ('vigencia_inicio', models.DateField(help_text='Inicio de vigencia', verbose_name='vigencia inicio')),
                ('vigencia_fin', models.DateField(help_text='Fin de vigencia', verbose_name='vigencia fin')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones', verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio (solo Específico)', on_delete=django.db.models.deletion.CASCADE, related_name='campos_clinicos', to='convenios.convention')),
                ('ambito_geografico_sanitario', models.ForeignKey(db_column='ambito_geografico_sanitario_id', help_text='Ámbito', on_delete=django.db.models.deletion.PROTECT, to='convenios.healthgeographicscope')),
                ('ipress', models.ForeignKey(db_column='ipress_id', help_text='Sede docente (establecimiento)', on_delete=django.db.models.deletion.PROTECT, to='convenios.ipress')),
                ('carrera_profesional', models.ForeignKey(db_column='carrera_profesional_id', help_text='Carrera / programa académico', on_delete=django.db.models.deletion.PROTECT, to='convenios.professionalcareer')),
                ('especialidad', models.ForeignKey(blank=True, db_column='especialidad_id', help_text='Especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='convenios.specialty')),
            ],
            options={
                'verbose_name': 'campo clínico',
                'db_table': 'campo_clinico',
            },
        ),
        migrations.CreateModel(
            name='TechnicalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], help_text='Resultado de la evaluación', max_length=20, verbose_name='resultado')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones', verbose_name='observaciones')),
                ('subsanacion', models.TextField(blank=True, help_text='Subsanación', verbose_name='subsanación')),
                ('fecha_evaluacion', models.DateField(help_text='Fecha de evaluación', verbose_name='fecha de evaluación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_tecnicas', to='convenios.convention')),
                ('evaluado_por', models.ForeignKey(db_column='evaluado_por', help_text='Responsable', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organo_minsa', models.ForeignKey(blank=True, db_column='organo_minsa_id', help_text='Unidad evaluadora (DIGEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='convenios.minsaorgan')),
            ],
            options={
                'verbose_name': 'evaluación técnica',
                'db_table': 'evaluacion_tecnica',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la universidad', max_length=255, verbose_name='nombre')),
                ('siglas', models.CharField(blank=True, help_text='Siglas', max_length=50, verbose_name='siglas')),
                ('codigo_inei', models.CharField(blank=True, help_text='Código INEI', max_length=20, verbose_name='código INEI')),
                ('fecha_constitucion', models.DateField(blank=True, help_text='Fecha de constitución', null=True, verbose_name='fecha de constitución')),
                ('fecha_autorizacion', models.DateField(blank=True, help_text='Fecha de autorización', null=True, verbose_name='fecha de autorización')),
                ('numero_resolucion', models.CharField(blank=True, help_text='Número de resolución', max_length=100, verbose_name='número de resolución')),
                ('direccion_legal', models.CharField(blank=True, help_text='Dirección legal', max_length=500, verbose_name='dirección legal')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=30, verbose_name='teléfono')),
                ('correo_institucional', models.CharField(blank=True, help_text='Correo institucional', max_length=255, verbose_name='correo institucional')),
                ('referencia_logo', models.CharField(blank=True, help_text='Referencia externa del logo (repositorio externo)', max_length=500, verbose_name='referencia del logo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo_autorizacion', models.ForeignKey(db_column='tipo_autorizacion_id', help_text='Licenciada / Denegada / Pendiente', on_delete=django.db.models.deletion.PROTECT, to='convenios.authorizationtype')),
                ('tipo_entidad', models.ForeignKey(db_column='tipo_entidad_id', help_text='Universidad / Escuela posgrado / Escuela superior / Instituto', on_delete=django.db.models.deletion.PROTECT, to='convenios.universityentitytype')),
                ('tipo_gestion', models.ForeignKey(db_column='tipo_gestion_id', help_text='Pública / privada', on_delete=django.db.models.deletion.PROTECT, to='convenios.universitymanagementtype')),
            ],
            options={
                'verbose_name': 'universidad',
                'db_table': 'universidad',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='universidad',
            field=models.ForeignKey(db_column='universidad_id', help_text='Universidad', on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='convenios.university'),
        ),
        migrations.CreateModel(
            name='UniversityAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la autoridad', max_length=255, verbose_name='nombre')),
                ('cargo', models.CharField(help_text='Cargo', max_length=150, verbose_name='cargo')),
                ('fecha_inicio_cargo', models.DateField(help_text='Inicio del cargo', verbose_name='fecha de inicio del cargo')),
                ('fecha_fin_cargo', models.DateField(blank=True, help_text='Fin del cargo', null=True, verbose_name='fecha de fin del cargo')),
                ('numero_resolucion', models.CharField(blank=True, help_text='Número de resolución de designación', max_length=100, verbose_name='número de resolución')),
                ('referencia_documento_resolucion', models.CharField(blank=True, help_text='Referencia externa del PDF de la resolución', max_length=500, verbose_name='referencia del documento de resolución')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('universidad', models.ForeignKey(db_column='universidad_id', help_text='Universidad', on_delete=django.db.models.deletion.CASCADE, related_name='autoridades', to='convenios.university')),
            ],
            options={
                'verbose_name': 'autoridad de universidad',
                'db_table': 'autoridad_universidad',
            },
        ),
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del local', max_length=255, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=500, verbose_name='dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('region', models.ForeignKey(blank=True, db_column='region_id', help_text='Región', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='convenios.region')),
                ('universidad', models.ForeignKey(db_column='universidad_id', help_text='Universidad', on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='convenios.university')),
            ],
            options={
                'verbose_name': 'local de universidad',
                'db_table': 'local_universidad',
            },
        ),
        migrations.CreateModel(
            name='ConventionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.PositiveBigIntegerField(help_text='Identificador de la entidad participante', verbose_name='id objeto')),
                ('es_firmante', models.BooleanField(default=False, help_text='Indica si firma el convenio', verbose_name='es firmante')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='convenios.convention')),
                ('tipo_contenido', models.ForeignKey(db_column='tipo_contenido_id', help_text='Tipo de entidad participante', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tipo_autoridad_firmante', models.ForeignKey(blank=True, db_column='tipo_autoridad_firmante_id', help_text='Tipo de autoridad firmante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='convenios.signingauthoritytype')),
            ],
            options={
                'verbose_name': 'participante de convenio',
                'db_table': 'participante_convenio',
                'unique_together': {('convenio', 'tipo_contenido', 'id_objeto')},
            },
        ),
        migrations.CreateModel(
            name='UserEntityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.PositiveBigIntegerField(help_text='Identificador de la entidad asociada', verbose_name='id objeto')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('grupo', models.ForeignKey(db_column='grupo_id', help_text='Rol institucional', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group')),
                ('tipo_contenido', models.ForeignKey(db_column='tipo_contenido_id', help_text='Tipo de entidad asociada', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(db_column='usuario_id', help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_entidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario por entidad',
                'db_table': 'perfil_usuario_entidad',
                'unique_together': {('usuario', 'tipo_contenido', 'id_objeto', 'grupo')},
            },
        ),
    ]
