# Generated by Django 6.0.6 on 2026-06-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código UBIGEO INEI (6 dígitos)', max_length=6, unique=True, verbose_name='código')),
                ('departamento', models.CharField(help_text='Departamento', max_length=100, verbose_name='departamento')),
                ('provincia', models.CharField(help_text='Provincia', max_length=100, verbose_name='provincia')),
                ('distrito', models.CharField(help_text='Distrito', max_length=100, verbose_name='distrito')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'ubigeo',
                'db_table': 'ubigeo',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='executingunit',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=500, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=500, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='regionalorgan',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=500, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='executingunit',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo'),
        ),
        migrations.AddField(
            model_name='regionalorgan',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo'),
        ),
        migrations.AddField(
            model_name='university',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo'),
        ),
        migrations.AddField(
            model_name='universitycampus',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo'),
        ),
    ]
