# Generated by Django 6.0.6 on 2026-08-13 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0013_logo_imagefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='ClassificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de clasificación',
                'verbose_name_plural': 'tipos de clasificación',
                'db_table': 'tipo_clasificacion',
            },
        ),
        migrations.CreateModel(
            name='Microred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la microred (único dentro de la red)', max_length=50, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre de la microred', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'microred',
                'verbose_name_plural': 'microredes',
                'db_table': 'microred',
                'ordering': ['red', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='ipress',
            name='cantidad_camas',
            field=models.PositiveIntegerField(blank=True, help_text='Número de camas del establecimiento', null=True, verbose_name='cantidad de camas'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud (coordenada geográfica)', max_digits=9, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud (coordenada geográfica)', max_digits=9, null=True, verbose_name='longitud'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='numero_ruc',
            field=models.CharField(blank=True, help_text='RUC (11 dígitos; texto para conservar ceros a la izquierda)', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='El RUC debe tener exactamente 11 dígitos numéricos.')], verbose_name='número de RUC'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria_id', help_text='Categoría del establecimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipress_por_categoria', to='convenios.category'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='tipo_clasificacion',
            field=models.ForeignKey(blank=True, db_column='tipo_clasificacion_id', help_text='Tipo de clasificación del establecimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipress_por_clasificacion', to='convenios.classificationtype'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='microred',
            field=models.ForeignKey(blank=True, db_column='microred_id', help_text='Microred a la que pertenece el establecimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipress_por_microred', to='convenios.microred'),
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la red (único dentro del ámbito)', max_length=50, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre de la red', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('ambito_geografico_sanitario', models.ForeignKey(db_column='ambito_geografico_sanitario_id', help_text='Ámbito geográfico sanitario al que pertenece la red', on_delete=django.db.models.deletion.PROTECT, related_name='redes', to='convenios.healthgeographicscope')),
            ],
            options={
                'verbose_name': 'red',
                'verbose_name_plural': 'redes',
                'db_table': 'red',
                'ordering': ['ambito_geografico_sanitario', 'codigo'],
                'unique_together': {('ambito_geografico_sanitario', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='microred',
            name='red',
            field=models.ForeignKey(db_column='red_id', help_text='Red a la que pertenece la microred', on_delete=django.db.models.deletion.PROTECT, related_name='microredes', to='convenios.red'),
        ),
        migrations.AlterUniqueTogether(
            name='microred',
            unique_together={('red', 'codigo')},
        ),
    ]
