# Generated by Django 6.0.6 on 2026-08-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0016_unify_organ_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executingunit',
            name='tipo_organo',
            field=models.ForeignKey(db_column='tipo_organo_id', help_text='Hospital / Instituto especializado / Red de salud (discriminador: UNIDAD_EJECUTORA)', on_delete=django.db.models.deletion.PROTECT, to='convenios.organtype'),
        ),
        migrations.AlterField(
            model_name='minsaorgan',
            name='tipo_organo',
            field=models.ForeignKey(db_column='tipo_organo_id', help_text='DIGEP / OGAJ / SG / VICEPAS (discriminador: MINSA)', on_delete=django.db.models.deletion.PROTECT, to='convenios.organtype'),
        ),
        migrations.AlterField(
            model_name='regionalorgan',
            name='tipo_organo',
            field=models.ForeignKey(db_column='tipo_organo_id', help_text='GERESA / DIRESA / DIRIS (discriminador: ORGANO_REGIONAL)', on_delete=django.db.models.deletion.PROTECT, to='convenios.organtype'),
        ),
        migrations.AlterField(
            model_name='university',
            name='tipo_entidad',
            field=models.ForeignKey(db_column='tipo_entidad_id', help_text='Universidad / Escuela posgrado / Escuela superior / Instituto (discriminador: UNIVERSIDAD)', on_delete=django.db.models.deletion.PROTECT, to='convenios.organtype'),
        ),
    ]
