# Generated by Django 6.0.6 on 2026-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0019_reorg_directorio_representantes_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='numero_ruc',
            field=models.CharField(blank=True, help_text='Número de RUC', max_length=11, verbose_name='número de RUC'),
        ),
    ]
