# Generated by Django 6.0.6 on 2026-08-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0020_university_numero_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('carrera_profesional', models.ForeignKey(db_column='carrera_profesional_id', help_text='Carrera profesional', on_delete=django.db.models.deletion.PROTECT, related_name='universidades', to='convenios.professionalcareer')),
                ('universidad', models.ForeignKey(db_column='universidad_id', help_text='Universidad', on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='convenios.university')),
            ],
            options={
                'verbose_name': 'carrera de universidad',
                'verbose_name_plural': 'carreras de universidad',
                'db_table': 'universidad_carrera',
                'unique_together': {('universidad', 'carrera_profesional')},
            },
        ),
    ]
