# Generated by Django 6.0.6 on 2026-08-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0024_executing_unit_gobierno_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalfieldregistration',
            name='fecha_resolucion_conapres',
            field=models.DateField(blank=True, help_text='Fecha de la resolución CONAPRES', null=True, verbose_name='fecha de resolución CONAPRES'),
        ),
        migrations.AddField(
            model_name='clinicalfieldregistration',
            name='numero_resolucion_conapres',
            field=models.CharField(blank=True, help_text='Número de la resolución CONAPRES que autoriza los campos clínicos de la sede', max_length=100, verbose_name='número de resolución CONAPRES'),
        ),
        migrations.AddField(
            model_name='convention',
            name='convenio_origen',
            field=models.ForeignKey(blank=True, db_column='convenio_origen_id', help_text='Convenio (Marco o Específico) que esta adenda amplía', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adendas', to='convenios.convention'),
        ),
        migrations.AddField(
            model_name='convention',
            name='es_adenda',
            field=models.BooleanField(default=False, help_text='Marca la fila como adenda de ampliación (derivable de convenio_origen; explícito para filtros)', verbose_name='es adenda'),
        ),
        migrations.AddField(
            model_name='convention',
            name='facultad',
            field=models.ForeignKey(blank=True, db_column='facultad_id', help_text='Facultad (de la universidad del Marco) parte del Convenio Específico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='convenios.faculty'),
        ),
        migrations.AddField(
            model_name='convention',
            name='unidad_ejecutora',
            field=models.ForeignKey(blank=True, db_column='unidad_ejecutora_id', help_text='Unidad ejecutora parte del Convenio Específico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='convenios.executingunit'),
        ),
    ]
