# Generated by Django 6.0.6 on 2026-08-30 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0025_convention_adenda_partes_resol_conapres'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycareer',
            name='facultad',
            field=models.ForeignKey(blank=True, db_column='facultad_id', help_text='Facultad de la universidad a la que pertenece la carrera', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carreras_facultad', to='convenios.faculty'),
        ),
    ]
