# Generated by Django 6.0.6 on 2026-09-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0030_finalize_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección de la facultad', max_length=255, verbose_name='dirección'),
        ),
    ]
