# Generated by Django 6.0.6 on 2026-09-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0032_universitycareer_facultad_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDirectoryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
                ('cargo_ejecutivo', models.ForeignKey(db_column='cargo_ejecutivo_id', help_text='Cargo ejecutivo habilitado', on_delete=django.db.models.deletion.PROTECT, related_name='organos_directorio', to='convenios.executiveposition')),
                ('organo_directorio', models.ForeignKey(db_column='organo_directorio_id', help_text='Órgano del directorio', on_delete=django.db.models.deletion.PROTECT, related_name='cargos_habilitados', to='convenios.organdirectory')),
            ],
            options={
                'verbose_name': 'cargo del órgano del directorio',
                'verbose_name_plural': 'cargos del órgano del directorio',
                'db_table': 'organo_directorio_cargo',
                'ordering': ['organo_directorio', 'cargo_ejecutivo'],
                'unique_together': {('organo_directorio', 'cargo_ejecutivo')},
            },
        ),
    ]
