# Generated by Django 6.0.6 on 2026-09-01 21:49
# Reordenado a mano: el unique_together nuevo referencia `organo_directivo`, por lo
# que ese campo debe crearse ANTES de aplicar el AlterUniqueTogether. También se
# libera primero el unique_together viejo (sobre `organo`) para poder quitar el campo.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0033_organdirectoryposition'),
    ]

    operations = [
        # 1 — Liberar el unique_together viejo (sobre `organo`) antes de quitar el campo.
        migrations.AlterUniqueTogether(
            name='executiveposition',
            unique_together=set(),
        ),
        # 2 — Quitar el FK a categoría (`organo`).
        migrations.RemoveField(
            model_name='executiveposition',
            name='organo',
        ),
        # 3 — Agregar el FK al órgano directivo concreto (nullable).
        migrations.AddField(
            model_name='executiveposition',
            name='organo_directivo',
            field=models.ForeignKey(blank=True, db_column='organo_directivo_id', help_text='Órgano directivo (del directorio) al que pertenece el cargo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='convenios.organdirectory', verbose_name='órgano directivo'),
        ),
        # 4 — Nuevo unique_together sobre el campo ya existente.
        migrations.AlterUniqueTogether(
            name='executiveposition',
            unique_together={('organo_directivo', 'nombre_masculino')},
        ),
        # 5 — Nueva ordenación por defecto.
        migrations.AlterModelOptions(
            name='executiveposition',
            options={'ordering': ['organo_directivo', 'nombre_masculino'], 'verbose_name': 'cargo ejecutivo'},
        ),
        # 6 — Eliminar la tabla puente retirada.
        migrations.DeleteModel(
            name='OrganDirectoryPosition',
        ),
    ]
