# Generated by Django 6.0.6 on 2026-09-02 17:39
# Editada a mano (Fase A): se sustituye el RemoveField+AddField autogenerado por un
# RenameField (codigo → nomenclatura) para preservar los datos existentes. Orden:
# 1) RenameField, 2) AddField ×2 (representante e historial), 3) CreateModel.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0034_alter_executiveposition_options_and_more'),
    ]

    operations = [
        # 1 — Renombrar `codigo` → `nomenclatura` (preserva la columna y sus datos).
        migrations.RenameField(
            model_name='convention',
            old_name='codigo',
            new_name='nomenclatura',
        ),
        # Ajustar los atributos del campo renombrado (verbose_name, help_text).
        migrations.AlterField(
            model_name='convention',
            name='nomenclatura',
            field=models.CharField(blank=True, help_text='Nomenclatura oficial del Convenio Marco (se asigna al aprobar DIGEP)', max_length=50, verbose_name='nomenclatura'),
        ),
        # 2 — Nueva resolución de facultades en representante e historial.
        migrations.AddField(
            model_name='organrepresentative',
            name='numero_resolucion_facultades',
            field=models.CharField(blank=True, help_text='Número de resolución que otorga facultades al representante', max_length=100, verbose_name='número de resolución de facultades'),
        ),
        migrations.AddField(
            model_name='organrepresentativehistory',
            name='numero_resolucion_facultades',
            field=models.CharField(blank=True, help_text='Número de resolución que otorga facultades al representante', max_length=100, verbose_name='número de resolución de facultades'),
        ),
        # 3 — Nueva tabla de partes firmantes estructuradas.
        migrations.CreateModel(
            name='ConventionParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('MINSA', 'MINSA'), ('UNIVERSIDAD', 'Universidad'), ('GOBIERNO_REGIONAL', 'Gobierno regional'), ('UNIDAD_EJECUTORA', 'Unidad ejecutora'), ('FACULTAD', 'Facultad')], db_column='rol', help_text='Rol institucional de la parte firmante', max_length=20, verbose_name='rol de la parte')),
                ('orden', models.PositiveSmallIntegerField(db_column='orden', default=1, help_text='Orden de firma dentro del rol (apoderado = 2)', verbose_name='orden de firma')),
                ('es_firmante', models.BooleanField(db_column='es_firmante', default=True, help_text='Indica si la parte firma el convenio', verbose_name='es firmante')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en', verbose_name='creado en')),
                ('cargo_ejecutivo', models.ForeignKey(blank=True, db_column='cargo_ejecutivo_id', help_text='Cargo ejecutivo del representante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.executiveposition')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio al que pertenece la parte', on_delete=django.db.models.deletion.CASCADE, related_name='partes_firmantes', to='convenios.convention')),
                ('organo_directorio', models.ForeignKey(db_column='organo_directorio_id', help_text='Órgano del directorio que representa la parte', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.organdirectory')),
                ('organo_representante', models.ForeignKey(blank=True, db_column='organo_representante_id', help_text='Representante que firma por la parte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.organrepresentative')),
            ],
            options={
                'verbose_name': 'parte de convenio',
                'verbose_name_plural': 'partes de convenio',
                'db_table': 'parte_convenio',
                'ordering': ['convenio', 'orden'],
                'unique_together': {('convenio', 'rol', 'orden')},
            },
        ),
    ]
