# Generated by Django 6.0.6 on 2026-09-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0035_convention_parties_nomenclatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipress',
            name='codigo_renipress',
            field=models.CharField(help_text='Código único RENIPRESS del establecimiento', max_length=20, unique=True, verbose_name='código RENIPRESS'),
        ),
    ]
