# Generated by Django 6.0.6 on 2026-09-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0039_organdirectory_organo_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executingunit',
            name='tipo_organo',
            field=models.ForeignKey(db_column='tipo_organo_id', help_text='Tipo de unidad ejecutora del directorio (organo=Unidad Ejecutora)', limit_choices_to={'organo__nombre': 'Unidad Ejecutora'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.organdirectory'),
        ),
        migrations.AlterField(
            model_name='university',
            name='tipo_entidad',
            field=models.ForeignKey(db_column='tipo_entidad_id', help_text='Tipo de entidad del directorio (organo=Universidad)', limit_choices_to={'organo__nombre': 'Universidad'}, on_delete=django.db.models.deletion.PROTECT, to='convenios.organdirectory'),
        ),
    ]
