# Generated by Django 6.0.6 on 2026-09-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0052_university_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcareer',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de visualización en el listado (menor primero)', verbose_name='orden'),
        ),
    ]
