# Generated by Django 6.0.6 on 2026-08-14 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la actividad de calendario', max_length=255, verbose_name='nombre')),
                ('detalle', models.TextField(blank=True, help_text='Descripción o detalle de la actividad', verbose_name='detalle')),
                ('numero_orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación (no único; usado en el ordenamiento por defecto)', verbose_name='número de orden')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la ventana', verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la ventana. NULL = ventana abierta (sin fecha de cierre)', null=True, verbose_name='fecha de fin')),
                ('controla_acceso', models.BooleanField(default=False, help_text='Si es verdadero, la actividad gobierna la escritura de sus content_types', verbose_name='controla acceso')),
                ('activo', models.BooleanField(default=True, help_text='Activación / baja lógica de la actividad', verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por', help_text='Usuario que actualizó la actividad por última vez', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_types', models.ManyToManyField(blank=True, db_table='actividad_calendario_content_type', help_text='Módulos/modelos que la actividad referencia y, si controla_acceso=True, gobierna', related_name='+', to='contenttypes.contenttype')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', help_text='Usuario que creó la actividad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsables', models.ManyToManyField(blank=True, db_table='actividad_calendario_responsable', help_text='Roles responsables de la actividad', related_name='actividades_calendario_responsable', to='auth.group')),
            ],
            options={
                'verbose_name': 'actividad de calendario',
                'verbose_name_plural': 'actividades de calendario',
                'db_table': 'actividad_calendario',
                'ordering': ['numero_orden', 'id'],
            },
        ),
    ]
