# Generated by Django 6.0.6 on 2026-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendaractivity',
            name='responsables',
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='responsables',
            field=models.TextField(blank=True, help_text='Responsables de la actividad (texto libre)', verbose_name='responsables'),
        ),
    ]
