# Generated by Django 6.0.6 on 2026-06-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden en el flujo', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'estado de actividad',
                'db_table': 'estado_actividad',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de actividad',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='ActivityStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambiado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora', verbose_name='cambiado en')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones', verbose_name='observación')),
                ('cambiado_por', models.ForeignKey(db_column='cambiado_por', help_text='Responsable', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='estado_id', help_text='Estado registrado', on_delete=django.db.models.deletion.PROTECT, to='actividades.activitystatus')),
            ],
            options={
                'verbose_name': 'historial de estado de actividad',
                'db_table': 'historial_estado_actividad',
            },
        ),
        migrations.CreateModel(
            name='ActivityValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('VALIDADA', 'Validada'), ('OBSERVADA', 'Observada'), ('RECHAZADA', 'Rechazada')], help_text='Resultado de la validación', max_length=20, verbose_name='resultado')),
                ('comentario', models.TextField(blank=True, help_text='Comentario de validación', verbose_name='comentario')),
                ('fecha_validacion', models.DateTimeField(help_text='Fecha y usuario validador', verbose_name='fecha de validación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('validado_por', models.ForeignKey(db_column='validado_por', help_text='Usuario validador', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'validación de actividad',
                'db_table': 'validacion_actividad',
            },
        ),
        migrations.CreateModel(
            name='TeachingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actividad', models.DateField(help_text='Fecha de la actividad', verbose_name='fecha de actividad')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o detalle', verbose_name='descripción')),
                ('carga_horaria', models.DecimalField(blank=True, decimal_places=2, help_text='Horas o carga horaria', max_digits=5, null=True, verbose_name='carga horaria')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado_actual', models.ForeignKey(db_column='estado_actual_id', help_text='Estado actual', on_delete=django.db.models.deletion.PROTECT, to='actividades.activitystatus')),
            ],
            options={
                'verbose_name': 'actividad docente-asistencial',
                'db_table': 'actividad_docente_asistencial',
            },
        ),
    ]
