# Generated by Django 6.0.6 on 2026-06-24 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('convenios', '0001_initial'),
        ('internados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingactivity',
            name='internado',
            field=models.ForeignKey(db_column='internado_id', help_text='Internado activo', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='internados.internship'),
        ),
        migrations.AddField(
            model_name='teachingactivity',
            name='interno',
            field=models.ForeignKey(db_column='interno_id', help_text='Interno', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='internados.intern'),
        ),
        migrations.AddField(
            model_name='teachingactivity',
            name='ipress',
            field=models.ForeignKey(db_column='ipress_id', help_text='Sede docente', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='convenios.ipress'),
        ),
        migrations.AddField(
            model_name='teachingactivity',
            name='rotacion',
            field=models.ForeignKey(blank=True, db_column='rotacion_id', help_text='Rotación autorizada asociada (si corresponde)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='internados.rotation'),
        ),
        migrations.AddField(
            model_name='teachingactivity',
            name='servicio_area',
            field=models.ForeignKey(db_column='servicio_area_id', help_text='Servicio, área o unidad', on_delete=django.db.models.deletion.PROTECT, to='internados.servicearea'),
        ),
        migrations.AddField(
            model_name='teachingactivity',
            name='tipo_actividad',
            field=models.ForeignKey(db_column='tipo_actividad_id', help_text='Tipo de actividad', on_delete=django.db.models.deletion.PROTECT, to='actividades.activitytype'),
        ),
        migrations.AddField(
            model_name='teachingactivity',
            name='tutor',
            field=models.ForeignKey(db_column='tutor_id', help_text='Tutor / docente responsable', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='internados.tutor'),
        ),
        migrations.AddField(
            model_name='activityvalidation',
            name='actividad',
            field=models.ForeignKey(db_column='actividad_id', help_text='Actividad validada', on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='actividades.teachingactivity'),
        ),
        migrations.AddField(
            model_name='activitystatushistory',
            name='actividad',
            field=models.ForeignKey(db_column='actividad_id', help_text='Actividad', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='actividades.teachingactivity'),
        ),
    ]
