# Generated by Django 6.0.6 on 2026-06-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de documento de identidad',
                'db_table': 'tipo_documento_identidad',
            },
        ),
        migrations.CreateModel(
            name='InternshipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden en el flujo', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'estado de internado',
                'db_table': 'estado_internado',
            },
        ),
        migrations.CreateModel(
            name='RotationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden en el flujo', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'estado de rotación',
                'db_table': 'estado_rotacion',
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único', max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Indica si está activo', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'servicio, área o unidad',
                'db_table': 'servicio_area',
            },
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número de documento de identidad', max_length=20, verbose_name='número de documento')),
                ('nombres', models.CharField(help_text='Nombres', max_length=150, verbose_name='nombres')),
                ('apellido_paterno', models.CharField(help_text='Apellido paterno', max_length=100, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, help_text='Apellido materno', max_length=100, verbose_name='apellido materno')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True, verbose_name='fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='M / F', max_length=1, verbose_name='sexo')),
                ('correo', models.CharField(blank=True, help_text='Correo electrónico', max_length=255, verbose_name='correo')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=30, verbose_name='teléfono')),
                ('codigo_universitario', models.CharField(blank=True, help_text='Código universitario / matrícula', max_length=50, verbose_name='código universitario')),
                ('anio_academico', models.PositiveSmallIntegerField(blank=True, help_text='Año académico', null=True, verbose_name='año académico')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('carrera_profesional', models.ForeignKey(db_column='carrera_profesional_id', help_text='Carrera / programa', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.professionalcareer')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.ForeignKey(blank=True, db_column='especialidad_id', help_text='Especialidad (segunda especialidad)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='convenios.specialty')),
                ('tipo_documento_identidad', models.ForeignKey(db_column='tipo_documento_identidad_id', help_text='Tipo de documento', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='internados.identitydocumenttype')),
                ('universidad', models.ForeignKey(db_column='universidad_id', help_text='Universidad de procedencia', on_delete=django.db.models.deletion.PROTECT, related_name='internos', to='convenios.university')),
            ],
            options={
                'verbose_name': 'interno',
                'db_table': 'interno',
                'unique_together': {('tipo_documento_identidad', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio', verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin (máx. 1 año)', verbose_name='fecha de fin')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones', verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('ambito_geografico_sanitario', models.ForeignKey(db_column='ambito_geografico_sanitario_id', help_text='Ámbito geográfico sanitario', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.healthgeographicscope')),
                ('campo_clinico', models.ForeignKey(db_column='campo_clinico_id', help_text='Campo clínico autorizado asignado', on_delete=django.db.models.deletion.PROTECT, related_name='internados', to='convenios.clinicalfield')),
                ('convenio', models.ForeignKey(db_column='convenio_id', help_text='Convenio Específico vigente que lo respalda', on_delete=django.db.models.deletion.PROTECT, related_name='internados', to='convenios.convention')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interno', models.ForeignKey(db_column='interno_id', help_text='Interno', on_delete=django.db.models.deletion.PROTECT, related_name='internados', to='internados.intern')),
                ('ipress', models.ForeignKey(db_column='ipress_id', help_text='Sede docente principal', on_delete=django.db.models.deletion.PROTECT, related_name='internados_principales', to='convenios.ipress')),
                ('estado_actual', models.ForeignKey(db_column='estado_actual_id', help_text='Estado actual', on_delete=django.db.models.deletion.PROTECT, to='internados.internshipstatus')),
            ],
            options={
                'verbose_name': 'internado',
                'db_table': 'internado',
            },
        ),
        migrations.CreateModel(
            name='InternshipStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambiado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora', verbose_name='cambiado en')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones', verbose_name='observación')),
                ('cambiado_por', models.ForeignKey(db_column='cambiado_por', help_text='Responsable', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='estado_id', help_text='Estado registrado', on_delete=django.db.models.deletion.PROTECT, to='internados.internshipstatus')),
                ('internado', models.ForeignKey(db_column='internado_id', help_text='Internado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='internados.internship')),
            ],
            options={
                'verbose_name': 'historial de estado de internado',
                'db_table': 'historial_estado_internado',
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rotacion', models.PositiveSmallIntegerField(help_text='Número de rotación (1–4, RN-9)', verbose_name='número de rotación')),
                ('fecha_inicio', models.DateField(help_text='Inicio de la rotación', verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fin de la rotación', verbose_name='fecha de fin')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones', verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('internado', models.ForeignKey(db_column='internado_id', help_text='Internado', on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones', to='internados.internship')),
                ('ipress_destino', models.ForeignKey(db_column='ipress_destino_id', help_text='Sede de destino', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ipress')),
                ('ipress_origen', models.ForeignKey(db_column='ipress_origen_id', help_text='Sede de origen', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ipress')),
                ('estado_actual', models.ForeignKey(db_column='estado_actual_id', help_text='Estado actual', on_delete=django.db.models.deletion.PROTECT, to='internados.rotationstatus')),
                ('servicio_area', models.ForeignKey(db_column='servicio_area_id', help_text='Servicio, área o unidad', on_delete=django.db.models.deletion.PROTECT, to='internados.servicearea')),
            ],
            options={
                'verbose_name': 'rotación',
                'db_table': 'rotacion',
            },
        ),
        migrations.CreateModel(
            name='RotationAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado'), ('RECHAZADO', 'Rechazado')], help_text='Resultado', max_length=20, verbose_name='resultado')),
                ('fecha_autorizacion', models.DateField(help_text='Fecha de autorización', verbose_name='fecha de autorización')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones', verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('autorizado_por', models.ForeignKey(db_column='autorizado_por', help_text='Usuario que registra la autorización', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participante_convenio', models.ForeignKey(db_column='participante_convenio_id', help_text='Autoridad suscrita en el Convenio Específico que autoriza', on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_rotacion', to='convenios.conventionparticipant')),
                ('rotacion', models.ForeignKey(db_column='rotacion_id', help_text='Rotación', on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='internados.rotation')),
            ],
            options={
                'verbose_name': 'autorización de rotación',
                'db_table': 'autorizacion_rotacion',
            },
        ),
        migrations.CreateModel(
            name='RotationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambiado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora', verbose_name='cambiado en')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones', verbose_name='observación')),
                ('cambiado_por', models.ForeignKey(db_column='cambiado_por', help_text='Responsable', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='estado_id', help_text='Estado registrado', on_delete=django.db.models.deletion.PROTECT, to='internados.rotationstatus')),
                ('rotacion', models.ForeignKey(db_column='rotacion_id', help_text='Rotación', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='internados.rotation')),
            ],
            options={
                'verbose_name': 'historial de estado de rotación',
                'db_table': 'historial_estado_rotacion',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número de documento de identidad', max_length=20, verbose_name='número de documento')),
                ('nombres', models.CharField(help_text='Nombres', max_length=150, verbose_name='nombres')),
                ('apellido_paterno', models.CharField(help_text='Apellido paterno', max_length=100, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, help_text='Apellido materno', max_length=100, verbose_name='apellido materno')),
                ('correo', models.CharField(blank=True, help_text='Correo electrónico', max_length=255, verbose_name='correo')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=30, verbose_name='teléfono')),
                ('numero_colegiatura', models.CharField(blank=True, help_text='Número de colegiatura', max_length=50, verbose_name='número de colegiatura')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('especialidad', models.ForeignKey(blank=True, db_column='especialidad_id', help_text='Especialidad del tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='convenios.specialty')),
                ('ipress', models.ForeignKey(blank=True, db_column='ipress_id', help_text='Establecimiento al que pertenece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutores', to='convenios.ipress')),
                ('tipo_documento_identidad', models.ForeignKey(db_column='tipo_documento_identidad_id', help_text='Tipo de documento', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='internados.identitydocumenttype')),
            ],
            options={
                'verbose_name': 'tutor',
                'db_table': 'tutor',
            },
        ),
        migrations.AddField(
            model_name='internship',
            name='tutor',
            field=models.ForeignKey(db_column='tutor_id', help_text='Tutor responsable actual', on_delete=django.db.models.deletion.PROTECT, related_name='internados', to='internados.tutor'),
        ),
        migrations.CreateModel(
            name='TutorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(help_text='Fecha del cambio', verbose_name='fecha de cambio')),
                ('motivo', models.TextField(help_text='Motivo del cambio', verbose_name='motivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('internado', models.ForeignKey(db_column='internado_id', help_text='Internado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_tutores', to='internados.internship')),
                ('responsable', models.ForeignKey(db_column='responsable_id', help_text='Responsable del cambio', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(db_column='tutor_id', help_text='Tutor asignado en este registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='internados.tutor')),
            ],
            options={
                'verbose_name': 'historial de tutor',
                'db_table': 'historial_tutor',
            },
        ),
    ]
