# Generated by Django 6.0.6 on 2026-06-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0005_ubigeo_executingunit_direccion_ipress_direccion_and_more'),
        ('internados', '0002_seed_catalogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=500, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='intern',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=500, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='ubigeo',
            field=models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo'),
        ),
    ]
