# Generated by Django 6.0.6 on 2026-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internados', '0011_seed_documentos_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexdocument',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del documento / declaración jurada', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='annexdocument',
            name='obligatorio',
            field=models.BooleanField(default=True, help_text='Indica si el documento es de presentación obligatoria', verbose_name='obligatorio'),
        ),
    ]
