# Generated by Django 6.0.6 on 2026-09-10 — reescrita para usar RENAME en lugar de DROP+ADD

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internados', '0027_tutor_convenio'),
    ]

    operations = [
        # 1. Renombra la clase Python del modelo y su entrada en django_content_type.
        migrations.RenameModel(
            old_name='AcademicPeriod',
            new_name='InternshipPeriod',
        ),
        # 2. Actualiza verbose_name.
        migrations.AlterModelOptions(
            name='internshipperiod',
            options={'verbose_name': 'periodo de internado'},
        ),
        # 3. Renombra la tabla de BD: periodo_academico → periodo_internado.
        migrations.AlterModelTable(
            name='internshipperiod',
            table='periodo_internado',
        ),
        # 4. Renombra el campo Python en Student (el estado de migración conserva
        #    db_column='periodo_academico_id'; la columna BD aún no cambia aquí).
        migrations.RenameField(
            model_name='student',
            old_name='periodo_academico',
            new_name='periodo_internado',
        ),
        # 5. Renombra la columna de BD: periodo_academico_id → periodo_internado_id.
        #    AlterField detecta el cambio de db_column y emite el RENAME COLUMN.
        migrations.AlterField(
            model_name='student',
            name='periodo_internado',
            field=models.ForeignKey(
                blank=True,
                db_column='periodo_internado_id',
                help_text='Periodo de internado (obligatorio para Pregrado — RN-19)',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='internados.internshipperiod',
            ),
        ),
    ]
