# Generated by Django 6.0.6 on 2026-09-16 14:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internados', '0029_remove_student_codigo_universitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nota_promedio_ponderado',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Nota promedio ponderado (escala 0–20, máximo 4 decimales)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='nota promedio ponderado'),
        ),
    ]
