# Generated by Django 6.0.6 on 2026-09-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0054_rename_organic_unit'),
        ('internados', '0031_fix_identity_document_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número de documento de identidad (único — un coordinador es una persona identificable)', max_length=20, unique=True, verbose_name='número de documento')),
                ('nombres', models.CharField(help_text='Nombres', max_length=150, verbose_name='nombres')),
                ('apellido_paterno', models.CharField(help_text='Apellido paterno', max_length=100, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, help_text='Apellido materno', max_length=100, null=True, verbose_name='apellido materno')),
                ('correo', models.CharField(blank=True, help_text='Correo electrónico', max_length=255, null=True, verbose_name='correo')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=30, null=True, verbose_name='teléfono')),
                ('numero_colegiatura', models.CharField(blank=True, help_text='Número de colegiatura', max_length=50, null=True, verbose_name='número de colegiatura')),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=500, null=True, verbose_name='dirección')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el coordinador está activo', verbose_name='activo')),
                ('especialidad', models.ForeignKey(blank=True, db_column='especialidad_id', help_text='Especialidad del coordinador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='convenios.specialty')),
                ('profesion', models.ForeignKey(blank=True, db_column='profesion_id', help_text='Profesión del coordinador (carrera profesional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.professionalcareer')),
                ('tipo_documento_identidad', models.ForeignKey(db_column='tipo_documento_identidad_id', help_text='Tipo de documento de identidad', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='internados.identitydocumenttype')),
                ('tutor', models.OneToOneField(blank=True, db_column='tutor_id', help_text='Tutor vinculado (si el coordinador también es tutor — RN-CRD-02)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinador', to='internados.tutor')),
                ('ubigeo', models.ForeignKey(blank=True, db_column='ubigeo_id', help_text='Ubicación geográfica (UBIGEO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='convenios.ubigeo')),
            ],
            options={
                'verbose_name': 'coordinador',
                'verbose_name_plural': 'coordinadores',
                'db_table': 'coordinador',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinador', models.ForeignKey(db_column='coordinador_id', help_text='Coordinador', on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='internados.coordinator')),
                ('ipress', models.ForeignKey(db_column='ipress_id', help_text='Sede docente (código RENIPRESS de 8 chars, PK textual de ipress)', on_delete=django.db.models.deletion.PROTECT, related_name='coordinadores_sede', to='convenios.ipress')),
                ('universidad', models.ForeignKey(db_column='universidad_id', help_text='Universidad', on_delete=django.db.models.deletion.PROTECT, related_name='coordinadores_sede', to='convenios.university')),
            ],
            options={
                'verbose_name': 'sede del coordinador',
                'verbose_name_plural': 'sedes del coordinador',
                'db_table': 'coordinador_sede',
                'unique_together': {('coordinador', 'universidad', 'ipress')},
            },
        ),
        migrations.CreateModel(
            name='CoordinatorTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinador_sede', models.ForeignKey(db_column='coordinador_sede_id', help_text='Asignación coordinador-sede', on_delete=django.db.models.deletion.CASCADE, related_name='tutores_asignados', to='internados.coordinatorsede')),
                ('tutor', models.ForeignKey(db_column='tutor_id', help_text='Tutor asignado', on_delete=django.db.models.deletion.PROTECT, related_name='coordinaciones', to='internados.tutor')),
            ],
            options={
                'verbose_name': 'tutor del coordinador',
                'verbose_name_plural': 'tutores del coordinador',
                'db_table': 'coordinador_tutor',
                'unique_together': {('coordinador_sede', 'tutor')},
            },
        ),
    ]
