# Generated by Django 6.0.6 on 2026-09-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='otp_code',
            field=models.CharField(blank=True, db_column='codigo_otp', default='', help_text='Hash del código OTP de email en tránsito; vacío cuando no hay OTP pendiente', max_length=8, verbose_name='código OTP transitorio'),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, db_column='otp_expira_en', help_text='Fecha y hora de expiración del OTP de email; nulo si no hay OTP pendiente', null=True, verbose_name='OTP expira en'),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='totp_secret',
            field=models.CharField(blank=True, db_column='secreto_totp', default='', help_text='Secreto base32 para generar códigos TOTP; nunca se expone en la API', max_length=64, verbose_name='secreto TOTP'),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='two_factor_enabled',
            field=models.BooleanField(db_column='autenticacion_doble_factor', default=False, help_text='Indica si el usuario tiene activado el segundo factor de autenticación', verbose_name='doble factor activo'),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('TOTP', 'Aplicación TOTP'), ('EMAIL', 'Correo electrónico')], db_column='metodo_doble_factor', default='', help_text='Método de segundo factor: TOTP (app autenticadora) o EMAIL (código por correo)', max_length=10, verbose_name='método de doble factor'),
        ),
    ]
