# Generated by Django 6.0.6 on 2026-09-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_usersecurity_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecurity',
            name='otp_code',
            field=models.CharField(blank=True, db_column='codigo_otp', default='', help_text='Hash SHA-256 del código OTP de email en tránsito; vacío cuando no hay OTP pendiente', max_length=64, verbose_name='código OTP transitorio'),
        ),
    ]
